# backend/routes/reports_route.py
from flask import Blueprint, jsonify, request, send_file
from fpdf import FPDF
from io import BytesIO
from datetime import datetime, timedelta
from flask_mail import Message
from extensions import mail
import random

reports_bp = Blueprint("reports_bp", __name__)

# Fake (but structured) historical attack data
CLASSES = ["DDoS", "VPN", "TOR", "I2P", "SQL Injection", "Malware"]

def generate_fake_data(days=7):
    today = datetime.now()
    data = []
    for i in range(days):
        date = (today - timedelta(days=i)).strftime("%Y-%m-%d")
        day_data = {cls: random.randint(20, 200) for cls in CLASSES}
        day_data["date"] = date
        data.append(day_data)
    return list(reversed(data))

ATTACK_DATA = generate_fake_data(14)

# --------------------------------------------------------
@reports_bp.route("/", methods=["GET"])
def reports_overview():
    total_attacks = sum(sum(v for k, v in day.items() if k != "date") for day in ATTACK_DATA)
    recent = ATTACK_DATA[-1]
    return jsonify({
        "total_attacks": total_attacks,
        "last_day": recent["date"],
        "last_day_total": sum(v for k, v in recent.items() if k != "date"),
    })

# --------------------------------------------------------
@reports_bp.route("/trend", methods=["GET"])
def attack_trend():
    trend = [{"date": d["date"], "attacks": sum(v for k, v in d.items() if k != "date")} for d in ATTACK_DATA]
    return jsonify(trend)

# --------------------------------------------------------
@reports_bp.route("/distribution", methods=["GET"])
def attack_distribution():
    total = {cls: sum(day.get(cls, 0) for day in ATTACK_DATA) for cls in CLASSES}
    return jsonify(total)

# --------------------------------------------------------
@reports_bp.route("/generate", methods=["GET"])
def generate_report_pdf():
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Adaptive AI NIDS - Attack Report", ln=True, align="C")

    pdf.set_font("Helvetica", "", 12)
    pdf.ln(8)
    pdf.cell(0, 10, f"Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
    pdf.ln(6)

    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 10, "Summary:", ln=True)
    pdf.set_font("Helvetica", "", 11)
    total = {cls: sum(day.get(cls, 0) for day in ATTACK_DATA) for cls in CLASSES}
    for cls, val in total.items():
        pdf.cell(0, 8, f" • {cls}: {val} attacks", ln=True)

    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 10)
    pdf.multi_cell(0, 8,
        "This report summarizes attack activity captured by the Adaptive AI NIDS system. "
        "It includes class-wise distribution and historical trend for the past two weeks.")

    # Output to memory
    buffer = BytesIO()
    pdf.output(buffer)
    buffer.seek(0)
    filename = f"NIDS_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    return send_file(buffer, as_attachment=True, download_name=filename, mimetype="application/pdf")

# --------------------------------------------------------
@reports_bp.route("/email", methods=["POST"])
def send_report_email():
    data = request.get_json()
    recipient = data.get("email")
    if not recipient:
        return jsonify({"error": "No recipient email provided"}), 400

    # Generate detailed PDF
    pdf_buffer = BytesIO()
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Adaptive AI NIDS - Full System Report", ln=True, align="C")
    pdf.ln(8)
    pdf.set_font("Helvetica", "", 12)
    pdf.cell(0, 10, "Summary of recent network activity:", ln=True)
    pdf.ln(5)

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Attack Distribution:", ln=True)
    total = {cls: sum(day.get(cls, 0) for day in ATTACK_DATA) for cls in CLASSES}
    pdf.set_font("Helvetica", "", 11)
    for cls, val in total.items():
        pdf.cell(0, 8, f" - {cls}: {val} attacks", ln=True)

    pdf.ln(6)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Recent Trend (last 7 days):", ln=True)
    pdf.set_font("Helvetica", "", 11)
    for d in ATTACK_DATA[-7:]:
        pdf.cell(0, 8, f"{d['date']}: {sum(v for k, v in d.items() if k != 'date')} total", ln=True)

    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 10)
    pdf.multi_cell(0, 8, "This automated report is generated by Adaptive AI NIDS. "
                         "It summarizes live detections, system diagnostics, and "
                         "AI-identified attack classes.")

    pdf.output(pdf_buffer)
    pdf_buffer.seek(0)

    try:
        msg = Message(
            subject="Adaptive AI NIDS - Full Report",
            recipients=[recipient],
            body="Attached is your Adaptive AI NIDS summary report with recent attack data.",
        )
        msg.attach("Adaptive_NIDS_Report.pdf", "application/pdf", pdf_buffer.read())
        mail.send(msg)
        return jsonify({"success": True, "message": f"Email sent to {recipient}"})
    except Exception as e:
        return jsonify({"error": str(e)}), 500



@reports_bp.route("/list", methods=["GET"])
def list_reports():
    reports = [
        {
            "id": 1,
            "name": "System Health Summary",
            "type": "System Health",
            "size": "420 KB",
            "date": datetime.now().strftime("%Y-%m-%d %H:%M"),
            "endpoint": "/api/reports/generate"
        },
        {
            "id": 2,
            "name": "Network Attack Analysis",
            "type": "Network Analysis",
            "size": "1.2 MB",
            "date": datetime.now().strftime("%Y-%m-%d %H:%M"),
            "endpoint": "/api/reports/generate"
        },
        {
            "id": 3,
            "name": "Threat Intelligence Summary",
            "type": "Threat Intelligence",
            "size": "620 KB",
            "date": datetime.now().strftime("%Y-%m-%d %H:%M"),
            "endpoint": "/api/reports/generate"
        },
    ]
    return jsonify(reports)





